### ISSUE TITLE
Script crashing when activating mod and not in vehicle 

### ISSUE THREAD

**Issue by CaptainFuture1** [chillnook/UberDriverMod#2]
As the headline states, the script crashes when accidentally activating the mod while on foot.

**Comment by chillnook** [comment]
Hey! A few questions. 
- What mod version are you running?
- Can you elaborate on what you mean by activating the mod? As it should be enabled by default with no issues.
-  Is this occurring when opening the menu, using the menu items, etc?

Thanks!

**If this issue is in 0.4a, please downgrade to 0.3.1a as 0.4a faced some issues in its release! Here is a link to the download:** [Download](https://github.com/chillnook/UberDriverMod/releases/tag/v0.4a)

**Comment by chillnook** [comment]
If this issue is on 0.4a, please downgrade to 0.3.1a as 0.4a faced some issues in its release! Here is a link to the download: [Download](https://github.com/chillnook/UberDriverMod/releases/tag/v0.4a)

**Comment by CaptainFuture1** [comment]
I'm on the newest version as found on GTA V mods. It happens when opening the menu while not in a vehicle. Multiple pop ups come up saying that there was a conflict. The script crashes.

Vielen Dank

Mit freundlichen Grüßen

Brian Bosch
________________________________

**Comment by chillnook** [comment]
Can you post a full list of your mods? I think another mod may be interfering and causing these issues!

**Comment by CaptainFuture1** [comment]
Sure, my mods are:

Realistic Weapon Sounds
Realism Dispatch Enhanced
Open all interiors
Scenario Groups
Natural Vision Remastered
Native Trainer
Helicopter bodyguards
All missions menu

Vielen Dank

Mit freundlichen Grüßen

Brian Bosch
________________________________

**Comment by CaptainFuture1** [comment]
And downloading the stable version fixed the issue. No more crashes.

Vielen Dank

Mit freundlichen Grüßen

Brian Bosch
________________________________

**Comment by chillnook** [comment]
Awesome, the next update should fix the issue! Thanks
